# Generated by Django 4.1.7 on 2023-05-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_alter_client_address_alter_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('rating_mean', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('sale_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.customer')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('sale_order_line_no', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.product')),
                ('sale_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.salesorder')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.customer'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.customer')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sklep.customer')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('products', models.ManyToManyField(related_name='carts', to='sklep.product')),
            ],
        ),
    ]
