# Generated by Django 4.1.7 on 2023-05-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
